### ISSUE TITLE
I've got an error when running project.

### ISSUE THREAD

**Issue by peetakarn** [Oyyou/Ideas#1]
![capture](https://user-images.githubusercontent.com/20243510/32368236-b0068b7a-c0b7-11e7-9ef9-8f7f70356024.PNG)

Thank you for helping.

**Comment by Oyyou** [comment]
You've got "Engine" set as the default project.

Go to the solution explorer, and set "TopDown" as the default project.

**Comment by peetakarn** [comment]
I get an error message.
![capture2](https://user-images.githubusercontent.com/20243510/32373173-9b8fbfb4-c0ca-11e7-97f9-90b48b75c659.PNG)

Thank you for your quick reply.

**Comment by Oyyou** [comment]
Okay, open the content.mgcb and find the file "BlackAndWhite.fx". You need to find that file, check it's properties, and set its "Build Action" to "Copy".

I'm going to remove that .fx file when I next get a chance.

**Comment by peetakarn** [comment]
It's working fine now, Thanks!
